import {StyleSheet, Dimensions} from 'react-native';
const styles = StyleSheet.create({
  ProductsSection: {
    marginHorizontal: 12,
  },
  selectedFilter: {
    borderRadius: 3,
    backgroundColor: 'white',
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.4,
    color: '#66cdaa',
    borderColor: '#66cdaa',
    borderWidth: 1,
    marginHorizontal: 1,
    marginRight: 4,
  },
  productImageContainer: {
    marginLeft: 5,
    marginTop: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  productsContainer: {
    marginTop: 2,
    marginLeft: 1,
    width: Dimensions.get('window').width / 2,
    borderColor: '#BCBCBC',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: {width: 1, height: 1},
    shadowOpacity: 0.4,
    shadowRadius: 3,
    elevation: 5,
    backgroundColor: '#fff',
  },
  productsImage: {
    width: 90,
    height: 80,
    borderRadius: 5,
    justifyContent: 'center',
    marginTop: 5,
  },
  gradeText: {
    color: '#66cdaa',
    fontSize: 14,
    fontWeight: 'bold',
    textAlign: 'left',
    borderWidth: 1,
    alignSelf: 'flex-start',
    paddingHorizontal: 6,
    borderRadius: 3,
    backgroundColor: '#f0f8ff',
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.4,
    shadowRadius: 3,
    // marginHorizontal: 5,
    // marginVertical: 5,
    borderColor: 'lightgrey',
    backgroundColor: 'white',
    marginTop: 5,
  },
  addToCartButton: {
    width: 190,
    borderColor: '#1E90FF',
    fontSize: 14,
    fontWeight: '700',
    marginRight: 5,
    backgroundColor: '#ffff',
    borderWidth: 1,
    textAlign: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 5,
    marginVertical: 5,
    color: '#1E90FF',
    height: 30,
  },
  productsTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'left',
    color: 'black',
    paddingBottom: 4,
    marginHorizontal: 5,
  },
  ProductListingContainer: {
    backgroundColor: '#ffffff',
    flex: 1,
  },
  grade: {
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#D3D3D3',
    width: '62%',
    borderRadius: 5,
    paddingHorizontal: 4,
  },
  gradeListing: {
    // backgroundColor: 'red',
    display: 'flex',
    flexDirection: 'row',
    width: 50,
  },
  detaillisting: {
    marginVertical: 10,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    flex: 1,
    paddingHorizontal: 50,
  },
  image: {
    backgroundColor: 'green',
  },
  text: {
    backgroundColor: 'blue',
  },
  heart: {
    backgroundColor: 'pink',
  },
  Surface: {
    padding: 8,
    height: 80,
    width: 80,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 4,
  },
  boxview: {
    flex: 1,
    marginRight: 15,
    marginTop: 2,
    marginLeft: 1,
    paddingHorizontal: 5,
    // width: 80,
    // height: 80,
    justifyContent: 'center',
    // alignItems: 'flex-start',
    alignSelf: 'center',
    width: '90%',
    borderRadius: 5,
    shadowColor: '#000',
    shadowOffset: {width: 1, height: 1},
    shadowOpacity: 0.4,
    shadowRadius: 3,
    elevation: 5,
    backgroundColor: '#fff',
    paddingBottom: 8,
  },
  textgrey: {
    fontSize: 14,
    marginTop: 2,
    color: 'grey',
  },
  view: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 5,
    marginTop: 5,
  },
});
export default styles;
